name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
      - run: wasm-pack test --node
      - run: wasm-pack test --headless --chrome
      - run: wasm-pack test --headless --firefox

      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: 'js-example-use/package.json'
          node-version: 18
          cache: 'npm'
      - run: npm install
        working-directory: js-example-use
      - name: Build
        working-directory: js-example-use
        run: npm run build
