name: Test-WASM-PACK

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: wasm-pack build
      - run: npm adduser --always-auth --auth-type=oauth
      - run: wasm-pack publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
