name: Test WASM PACK

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo install cargo-semver --vers 1.0.0-alpha.3

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v2.0.0
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}
      - name: wasm-pack stuff
        run: wasm-pack build
      - run: wasm-pack login